---
openapi: 3.0.2
info:
    title: Timeline Service API
    description: |-
        The [Timeline Service](https://projectronin.atlassian.net/wiki/spaces/ENG/pages/1990393974/Timeline+Service):
            - consumes events containing reported symptoms data from [CTS](https://projectronin.atlassian.net/wiki/spaces/ENG/pages/1969750023/Clinician+Triage+Service) (Clinician Triage Service)
            - stores a subset of that information needed to track timeline-oriented symptoms data
            - serves said data pre-transformed/optimized to the frontend

        To authorize requests in local & dev environments from this document, click `Authorize`, copy/paste the below auth token, and click `Authorize` again.
        
        ```
        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTMzMjgzMjAsImlzcyI6IlNla2kiLCJqdGkiOiIycm9zcW05M2VlbmFwYmlrZm8wMXFrODEiLCJzdWIiOiIxNTFhMjUwOS1lNjllLTQwNDMtYmJhOC1kYmY5ODhkZGE1NTUiLCJ0ZW5hbnRpZCI6ImFwcG9zbmQifQ.gmX_Ad6sgTTW0iogI4kwuhYYbnpn5HGIE5RZxi56Ojs
        ```
    contact:
        name: Team APEX (in Slack)
        url: https://projectronin.slack.com/archives/C03QLMWKE12
    version: 0.0.5
externalDocs:
    description: Find out more about Timeline Service
    url: https://projectronin.atlassian.net/wiki/spaces/ENG/pages/1990393974/Timeline+Service
servers:
    - url: /api/v1
tags:
    - name: Timeline Event
      description: Generic timeline events of various types
    - name: Timeline Metadata
      description: Patient metadata pertaining to timeline
paths:
    "/tenants/{tenantId}/patients/{patientId}/timeline/metadata":
        parameters:
            - name: patientId
              in: path
              description: ID of patient to query by
              required: true
              schema:
                  type: string
              example: 022628c4-d1ea-4ae3-9a6b-04c30ac4f903
            - name: tenantId
              in: path
              description: ID of tenant patient and clinician belongs to
              required: true
              schema:
                  type: string
                  example: apposnd
        get:
            security:
                - Seki: []
            description: Get timeline metadata pertaining to when date ranges start/end
                for a patient
            operationId: getTimelineMetadata
            tags:
                - Timeline Metadata
            summary: Get timeline metadata pertaining to specified patient
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/TimelineMetadataResponse"
                '401':
                    description: Unauthorized, you didn’t send your token
                '403':
                    description: Forbidden, you sent your token and I have determined you unworthy
                '404':
                    description: Patient not found, either that resource doesn’t exist or I don’t want
                        to tell you it does and you don’t have access
                '500':
                    description: Unexpected error.
    "/tenants/{tenantId}/patients/{patientId}/timeline/symptoms":
        parameters:
            - name: patientId
              in: path
              description: ID of patient to query by
              required: true
              schema:
                  type: string
              example: 022628c4-d1ea-4ae3-9a6b-04c30ac4f903
            - name: tenantId
              in: path
              description: ID of tenant patient and clinician belongs to
              required: true
              schema:
                  type: string
              example: apposnd
        get:
            security:
                - Seki: []
            tags:
                - Timeline Event
            summary: Get symptom timeline events
            description: Get all timeline events where (a) the timeline timestamp is between
                the specified start & end timestamps, and (b) where the timeline event type
                is `symptoms`.
            operationId: getSymptomTimelineEvents
            parameters:
                - name: start
                  in: query
                  description: UTC timestamp representing the (inclusive) starting point of
                      the date range by which to query timeline events. If not provided, no lower limit will be defined.
                  required: false
                  schema:
                      type: string
                      format: date-time
                      example: '2023-01-01T00:00:01Z'
                - name: end
                  in: query
                  description: UTC timestamp representing the (exclusive) ending point of the
                      date range by which to query timeline events. If not provided, no upper limit will be defined.
                  required: false
                  schema:
                      type: string
                      format: date-time
                      example: '2024-01-01T00:00:01Z'
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SymptomReportResponse"
                '401':
                    description: Unauthorized, you didn’t send your token
                '403':
                    description: Forbidden, you sent your token and I have determined you unworthy
                '404':
                    description: Patient or tenant not foundNot found, either that resource doesn’t exist or I don’t want
                        to tell you it does and you don’t have access
                '500':
                    description: Unexpected error.
components:
    schemas:
        SymptomReportResponse:
            type: object
            required:
                - meta
                - data
            properties:
                meta:
                    type: string
                    example: "/api/v1/tenants/apposd/patients/apposd-43211234/timeline/symptoms?start=2023-01-01T00:00:01Z&end=2023-03-01T00:00:01Z"
                data:
                    type: array
                    items:
                        "$ref": "#/components/schemas/SymptomReport"
        SymptomReport:
            type: object
            required:
                - id
                - externalId
                - patientId
                - tenantId
                - alertState
                - completedOn
                - rowCreatedAt
                - rowUpdatedAt
                - reportedSymptoms
            properties:
                id:
                    type: string
                    format: uuid
                    example: 935a9879-e8ce-4c86-9dcc-1ecdc9722283
                externalId:
                    type: string
                    example: 4e3567c9-b445-4d58-b62e-a3d6b2df2fd8
                patientId:
                    type: string
                    example: cd2d37a5-7967-46b0-b4e7-d91c61aea861
                tenantId:
                    type: string
                    example: cd2d37a5-7967-46b0-b4e7-d91c61aea861
                alertState:
                    type: string
                    example: HIGH_ALERT
                completedOn:
                    type: string
                    format: date-time
                    example: '2023-04-20T21:04:36Z'
                rowCreatedAt:
                    type: string
                    format: date-time
                    example: '2023-04-20T21:04:36Z'
                rowUpdatedAt:
                    type: string
                    format: date-time
                    example: '2023-04-20T21:04:36Z'
                reportedSymptoms:
                    type: array
                    items:
                        "$ref": "#/components/schemas/SymptomReportSymptom"
        SymptomReportSymptom:
            type: object
            required:
                - id
                - symptomReportId
                - symptomId
                - rowCreatedAt
                - rowUpdatedAt
                - symptom
            properties:
                id:
                    type: string
                    format: uuid
                    example: 935a9879-e8ce-4c86-9dcc-1ecdc9722283
                symptomReportId:
                    type: string
                    format: uuid
                    example: '00544940-a455-441f-a926-6a2d5d5dad83'
                symptomId:
                    type: string
                    format: uuid
                    example: dc1005f7-d52f-4ef7-85ab-0e832a288aa9
                rowCreatedAt:
                    type: string
                    format: date-time
                    example: '2023-04-20T21:04:36Z'
                rowUpdatedAt:
                    type: string
                    format: date-time
                    example: '2023-04-20T21:04:36Z'
                symptom:
                    $ref: "#/components/schemas/Symptom"
        Symptom:
            type: object
            required:
                - id
                - code
                - displayName
                - displayOrder
                - rowCreatedAt
                - rowUpdatedAt
            properties:
                id:
                    type: string
                    format: uuid
                    example: 935a9879-e8ce-4c86-9dcc-1ecdc9722283
                code:
                    type: string
                    example: fatigue
                displayName:
                    type: string
                    example: Fatigue
                displayOrder:
                    type: integer
                    example: 3
                rowCreatedAt:
                    type: string
                    format: date-time
                    example: '2023-04-20T21:04:36Z'
                rowUpdatedAt:
                    type: string
                    format: date-time
                    example: '2023-04-20T21:04:36Z'
        PatientSymptom:
            type: object
            description: Patient metadata regarding a specific symptom
            required:
                - symptomId
                - lastReportedAt
            properties:
                symptomId:
                    type: string
                    format: uuid
                    example: 935a9879-e8ce-4c86-9dcc-1ecdc9722283
                lastReportedAt:
                    type: string
                    description: When the symptom was last reported for the patient
                    example: '2020-03-04T14:39:28Z'
        TimelineMetadataResponse:
            type: object
            required:
                - symptoms
                - patientSymptoms
                - dateRanges
            properties:
                symptoms:
                    type: array
                    items:
                        $ref: "#/components/schemas/Symptom"
                patientSymptoms:
                    type: array
                    items:
                        $ref: "#/components/schemas/PatientSymptom"
                dateRanges:
                    type: object
                    required:
                        - symptoms
                    properties:
                        symptoms:
                            type: object
                            required:
                                - start
                                - end
                            properties:
                                start:
                                    type: string
                                    example: '2020-03-04T14:39:28Z'
                                end:
                                    type: string
                                    example: '2020-03-04T14:39:28Z'
    securitySchemes:
        Seki:
            type: http
            scheme: bearer
            bearerFormat: JWT
