name: Rest Contract CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: build_and_test
    uses: projectronin/github/.github/workflows/rest_contract_cicd.yaml@master
    with:
      publish: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      nexus_user:      ${{ secrets.NEXUS_MAVEN_USER }}
      nexus_token:     ${{ secrets.NEXUS_MAVEN_TOKEN }}
